import Foundation

enum IdentitySwiftRenderer {
    static func render(output: IdentityOutputPolicy, identities: [IdentityPolicy]) -> String {
        var sections = [
            "// Generated by `swift run wck identity generate`.\n"
                + "// Source: \(IdentityGenerator.policyPath).\n"
                + "// Do not edit."
        ]
        if !output.imports.isEmpty {
            sections.append(output.imports.sorted().map { "import \($0)" }.joined(separator: "\n"))
        }
        sections.append(contentsOf: identities.map(renderIdentity))
        sections.append(contentsOf: identities.compactMap(renderExtension))
        return sections.joined(separator: "\n\n") + "\n"
    }

    private static func renderIdentity(_ identity: IdentityPolicy) -> String {
        var members: [String] = []
        if let typealiasAccess = identity.integerLiteral?.typealiasAccess {
            members.append(
                renderDocumentation(identity.documentation?.integerLiteralType)
                    + "\(typealiasAccess.rawValue) typealias IntegerLiteralType = "
                    + (identity.integerLiteral?.type ?? identity.rawType)
            )
        }
        members.append(
            renderDocumentation(identity.documentation?.storage)
                + "\(identity.storageAccess.rawValue) let \(identity.effectiveStorageName): "
                + identity.rawType
        )
        members.append(
            renderInitializer(
                IdentityInitializerOverride(
                    access: identity.constructorAccess,
                    label: identity.effectiveConstructorLabel,
                    parameter: identity.constructorParameter,
                    type: identity.effectiveConstructorType,
                    expression: identity.effectiveConstructorExpression
                ),
                storageName: identity.effectiveStorageName,
                documentation: identity.documentation?.constructor
            )
        )
        members.append(
            contentsOf: identity.additionalInitializers.map { initializer in
                renderInitializer(
                    initializer,
                    storageName: identity.effectiveStorageName,
                    documentation: nil
                )
            })
        if let literal = identity.integerLiteral {
            let valueType = literal.type ?? identity.rawType
            let body =
                literal.assignDirectly
                ? "self.\(identity.effectiveStorageName) = value"
                : "self.init(\(identity.effectiveConstructorLabel): value)"
            members.append(
                renderDocumentation(identity.documentation?.integerLiteral)
                    + "\(literal.access.rawValue) init(integerLiteral value: \(valueType)) {\n"
                    + "    \(body)\n}"
            )
        }
        if let description = identity.description, !description.inExtension {
            members.append(renderDescription(description, identity: identity))
        }

        let header = renderHeader(
            prefix: "\(identity.access.rawValue) struct \(identity.type)",
            conformances: identity.directConformances
        )
        let body = members.map(indent).joined(separator: "\n\n")
        return renderDocumentation(identity.documentation?.summary)
            + identity.attributes.joined(separator: "\n")
            + (identity.attributes.isEmpty ? "" : "\n")
            + "\(header)\n\(body)\n}"
    }

    private static func renderExtension(_ identity: IdentityPolicy) -> String? {
        let conformances = identity.generatedExtensionConformances
        guard !conformances.isEmpty else { return nil }
        let header = renderHeader(prefix: "extension \(identity.type)", conformances: conformances)
        guard let description = identity.description, description.inExtension else {
            return "\(header)\n}"
        }
        return "\(header)\n\(indent(renderDescription(description, identity: identity)))\n}"
    }

    private static func renderInitializer(
        _ initializer: IdentityInitializerOverride,
        storageName: String,
        documentation: String?
    ) -> String {
        renderDocumentation(documentation)
            + "\(initializer.access.rawValue) init(\(initializer.label) "
            + "\(initializer.parameter): \(initializer.type)) {\n"
            + "    \(storageName) = \(initializer.expression)\n}"
    }

    private static func renderDescription(
        _ description: IdentityDescriptionPolicy,
        identity: IdentityPolicy
    ) -> String {
        let expression =
            description.expression
            ?? "\"\(description.prefix ?? "")\\(\(identity.effectiveStorageName))\""
        return renderDocumentation(identity.documentation?.description)
            + "\(description.effectiveAccess(typeAccess: identity.access).rawValue) "
            + "var description: String {\n    \(expression)\n}"
    }

    private static func renderHeader(prefix: String, conformances: [String]) -> String {
        let compact = "\(prefix): \(conformances.joined(separator: ", ")) {"
        guard compact.count > 100 else { return compact }
        return "\(prefix):\n" + conformances.map { "    \($0)" }.joined(separator: ",\n") + "\n{"
    }

    private static func renderDocumentation(_ text: String?) -> String {
        text.map { "/// \($0)\n" } ?? ""
    }

    private static func indent(_ source: String) -> String {
        source.split(separator: "\n", omittingEmptySubsequences: false)
            .map { "    \($0)" }.joined(separator: "\n")
    }
}

enum IdentityAuditRenderer {
    static func render(
        policy: IdentityGenerationPolicy,
        manualAudit: IdentityAuditManifest
    ) throws -> String {
        let generated: [IdentityAuditEntry] = policy.identities.compactMap { identity in
            guard let category = identity.auditCategory else { return nil }
            return IdentityAuditEntry(
                type: identity.type,
                category: category,
                constructor: identity.constructorAccess,
                storage: identity.effectiveStorageName,
                storageVisibility: identity.storageAccess
            )
        }
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys, .withoutEscapingSlashes]
        let sortedIdentities = (generated + manualAudit.identities).sorted { $0.type < $1.type }
        let rows = try sortedIdentities.map { identity -> String in
            let data = try encoder.encode(identity)
            guard let row = String(data: data, encoding: .utf8) else {
                throw ToolError(
                    "failed to encode identity audit entry", exitCode: ToolExitCode.data)
            }
            return "    \(row)"
        }
        return "{\n  \"identities\": [\n\(rows.joined(separator: ",\n"))\n  ]\n}\n"
    }
}
