import Foundation

/// A checked-in file rendered from the identity generation policy.
public struct GeneratedIdentityFile: Equatable, Sendable {
    /// The repository-relative output path.
    public let path: String

    /// The complete generated contents.
    public let contents: String

    /// Creates a generated identity file.
    public init(path: String, contents: String) {
        self.path = path
        self.contents = contents
    }
}

/// Generates concrete identity wrappers without replacing their domain-specific types.
public struct IdentityGenerator {
    static let declarationHeader =
        "// Generated by `swift run wck identity generate`.\n"
        + "// Source: \(policyPath).\n"
        + "// Do not edit.\n"

    /// The repository-relative path to the identity generation policy.
    public static let policyPath = "identities/generation-policy.json"

    /// The repository-relative path to audit metadata for handwritten identities.
    public static let manualAuditPath = "identities/manual-identity-categories.json"

    /// The repository-relative path to the combined generated identity audit manifest.
    public static let auditOutputPath = "docs/identity-categories.json"

    /// The repository that owns the policy and checked-in outputs.
    public let repository: Repository

    /// The filesystem used to read and write generator inputs and outputs.
    public let fileSystem: FileSystem

    /// Creates an identity generator for a repository.
    public init(repository: Repository, fileSystem: FileSystem = LocalFileSystem()) {
        self.repository = repository
        self.fileSystem = fileSystem
    }

    /// Renders every generated output without changing the checkout.
    public func render() throws -> [GeneratedIdentityFile] {
        let policy: IdentityGenerationPolicy = try decode(Self.policyPath)
        let manualAudit: IdentityAuditManifest = try decode(Self.manualAuditPath)
        try policy.validate(manualAudit: manualAudit)

        var files = try policy.outputs.map { output in
            let identities = policy.identities
                .filter { $0.output == output.id }
                .sorted { $0.type < $1.type }
            guard !identities.isEmpty else {
                throw ToolError(
                    "identity generation output has no declarations: \(output.id)",
                    exitCode: ToolExitCode.data
                )
            }
            return GeneratedIdentityFile(
                path: output.path,
                contents: IdentitySwiftRenderer.render(output: output, identities: identities)
            )
        }
        files.append(
            GeneratedIdentityFile(
                path: Self.auditOutputPath,
                contents: try IdentityAuditRenderer.render(
                    policy: policy,
                    manualAudit: manualAudit
                )
            )
        )
        return files.sorted { $0.path < $1.path }
    }

    /// Replaces the checked-in files with freshly rendered output.
    public func generate() throws {
        let files = try render()
        let expectedDeclarationPaths = Set(
            files.lazy.filter { $0.path != Self.auditOutputPath }.map(\.path)
        )
        let ownedDeclarationPaths = try discoverOwnedDeclarationPaths()
        let unexpectedDeclarationPaths =
            ownedDeclarationPaths
            .subtracting(expectedDeclarationPaths)
            .sorted()

        try preflightDestinations(
            files,
            unexpectedDeclarationPaths: unexpectedDeclarationPaths
        )

        for file in files {
            try fileSystem.writeText(file.contents, to: repository.url(file.path))
        }
        for path in unexpectedDeclarationPaths {
            try fileSystem.removeItem(repository.url(path))
        }
    }

    /// Verifies that the checked-in files match the current policy.
    public func verifyGenerated() throws {
        var failures: [String] = []
        let files = try render()
        let expectedDeclarationPaths = Set(
            files.lazy.filter { $0.path != Self.auditOutputPath }.map(\.path)
        )
        for file in files {
            let url = repository.url(file.path)
            if !fileSystem.exists(url) {
                failures.append("missing generated file: \(file.path)")
            } else if try fileSystem.readText(url) != file.contents {
                failures.append("changed generated file: \(file.path)")
            }
        }
        for path in try discoverOwnedDeclarationPaths()
            .subtracting(expectedDeclarationPaths)
            .sorted()
        {
            failures.append("unexpected generated file: \(path)")
        }
        guard failures.isEmpty else {
            throw ToolError(
                "generated identity declarations are not up to date\n"
                    + failures.joined(separator: "\n"),
                exitCode: ToolExitCode.data
            )
        }
    }

    private func preflightDestinations(
        _ files: [GeneratedIdentityFile],
        unexpectedDeclarationPaths: [String]
    ) throws {
        var failures: [String] = []
        for file in files where file.path != Self.auditOutputPath {
            let url = repository.url(file.path)
            guard fileSystem.exists(url) else { continue }
            if !(try fileSystem.readText(url)).hasPrefix(Self.declarationHeader) {
                failures.append(
                    "refusing to replace a file not owned by identity generation: \(file.path)")
            }
        }
        for path in unexpectedDeclarationPaths where !IdentityGenerationPolicy.isOutputPath(path) {
            failures.append(
                "refusing to remove generated file outside an approved directory: \(path)")
        }
        guard failures.isEmpty else {
            throw ToolError(failures.joined(separator: "\n"), exitCode: ToolExitCode.data)
        }
    }

    private func discoverOwnedDeclarationPaths() throws -> Set<String> {
        let sources = repository.url("Sources")
        var paths: Set<String> = []
        for url in try fileSystem.walk(sources, includingDirectories: false)
        where url.pathExtension == "swift" {
            if try fileSystem.readText(url).hasPrefix(Self.declarationHeader) {
                paths.insert(repository.relativePath(url))
            }
        }
        return paths
    }

    private func decode<Value: Decodable>(_ path: String) throws -> Value {
        let url = repository.url(path)
        guard fileSystem.exists(url) else {
            throw ToolError(
                "Missing identity generator input: \(path)", exitCode: ToolExitCode.data)
        }
        do {
            return try JSONDecoder().decode(Value.self, from: fileSystem.readData(url))
        } catch {
            throw ToolError(
                "Malformed identity generator input \(path): \(error)",
                exitCode: ToolExitCode.data
            )
        }
    }
}

struct IdentityGenerationPolicy: Decodable {
    let outputs: [IdentityOutputPolicy]
    let identities: [IdentityPolicy]

    func validate(manualAudit: IdentityAuditManifest) throws {
        var failures: [String] = []
        appendDuplicates(outputs.map(\.id), label: "output id", failures: &failures)
        appendDuplicates(outputs.map(\.path), label: "output path", failures: &failures)
        appendDuplicates(identities.map(\.type), label: "identity type", failures: &failures)
        appendDuplicates(
            manualAudit.identities.map(\.type),
            label: "manual identity audit type",
            failures: &failures
        )

        let outputIDs = Set(outputs.map(\.id))
        for output in outputs where !Self.isOutputPath(output.path) {
            failures.append("identity output is not a Swift file under Sources: \(output.path)")
        }
        for identity in identities {
            if !outputIDs.contains(identity.output) {
                failures.append("\(identity.type) references unknown output \(identity.output)")
            }
            if identity.access == .public, identity.auditCategory == nil {
                failures.append("\(identity.type) is missing an audit category")
            }
            if identity.access != .public, identity.auditCategory != nil {
                failures.append("\(identity.type) is not public but has an audit category")
            }
            identity.validateVisibility(failures: &failures)
            identity.validateDocumentation(failures: &failures)
        }
        let generatedAuditTypes = identities.compactMap { $0.auditCategory == nil ? nil : $0.type }
        let overlap = Set(generatedAuditTypes)
            .intersection(manualAudit.identities.map(\.type))
            .sorted()
        if !overlap.isEmpty {
            failures.append(
                "generated and manual identity audits overlap: \(overlap.joined(separator: ", "))")
        }
        guard failures.isEmpty else {
            throw ToolError(failures.joined(separator: "\n"), exitCode: ToolExitCode.data)
        }
    }

    private func appendDuplicates(
        _ values: [String],
        label: String,
        failures: inout [String]
    ) {
        let duplicates = Dictionary(grouping: values) { $0 }
            .filter { $0.value.count > 1 }.keys.sorted()
        if !duplicates.isEmpty {
            failures.append("duplicate \(label): \(duplicates.joined(separator: ", "))")
        }
    }

    static func isOutputPath(_ path: String) -> Bool {
        let components = path.split(separator: "/", omittingEmptySubsequences: false)
        guard components.count >= 4,
            components.first == "Sources",
            components.last?.hasSuffix(".swift") == true,
            components.dropLast().contains("Generated")
        else {
            return false
        }
        return !components.contains { $0.isEmpty || $0 == "." || $0 == ".." }
    }
}

struct IdentityOutputPolicy: Decodable {
    let id: String
    let path: String
    let imports: [String]
}

struct IdentityPolicy: Decodable {
    private enum CodingKeys: String, CodingKey {
        case type
        case output
        case access
        case rawType
        case storageName
        case storageAccess
        case constructorAccess
        case constructorLabel
        case constructorParameter
        case constructorType
        case constructorExpression
        case attributes
        case conformances
        case sharedIDConformance
        case sharedIDInExtension
        case extensionConformances
        case description
        case integerLiteral
        case additionalInitializers
        case documentation
        case auditCategory
    }

    let type: String
    let output: String
    let access: IdentityAccess
    let rawType: String
    let storageName: String?
    let storageAccess: IdentityAccess
    let constructorAccess: IdentityAccess
    let constructorLabel: String?
    let constructorParameter: String
    let constructorType: String?
    let constructorExpression: String?
    let attributes: [String]
    let conformances: [String]
    let sharedIDConformance: String?
    let sharedIDInExtension: Bool
    let extensionConformances: [String]
    let description: IdentityDescriptionPolicy?
    let integerLiteral: IdentityIntegerLiteralPolicy?
    let additionalInitializers: [IdentityInitializerOverride]
    let documentation: IdentityDocumentationPolicy?
    let auditCategory: IdentityAuditCategory?

    init(from decoder: any Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        type = try values.decode(String.self, forKey: .type)
        output = try values.decode(String.self, forKey: .output)
        access = try values.decode(IdentityAccess.self, forKey: .access)
        rawType = try values.decode(String.self, forKey: .rawType)
        storageName = try values.decodeIfPresent(String.self, forKey: .storageName)
        storageAccess = try values.decode(IdentityAccess.self, forKey: .storageAccess)
        constructorAccess = try values.decode(IdentityAccess.self, forKey: .constructorAccess)
        constructorLabel = try values.decodeIfPresent(String.self, forKey: .constructorLabel)
        constructorParameter = try values.decode(String.self, forKey: .constructorParameter)
        constructorType = try values.decodeIfPresent(String.self, forKey: .constructorType)
        constructorExpression = try values.decodeIfPresent(
            String.self,
            forKey: .constructorExpression
        )
        attributes = try values.decodeIfPresent([String].self, forKey: .attributes) ?? []
        conformances = try values.decode([String].self, forKey: .conformances)
        sharedIDConformance = try values.decodeIfPresent(
            String.self,
            forKey: .sharedIDConformance
        )
        sharedIDInExtension =
            try values.decodeIfPresent(Bool.self, forKey: .sharedIDInExtension) ?? false
        extensionConformances =
            try values.decodeIfPresent([String].self, forKey: .extensionConformances) ?? []
        description = try values.decodeIfPresent(
            IdentityDescriptionPolicy.self,
            forKey: .description
        )
        integerLiteral = try values.decodeIfPresent(
            IdentityIntegerLiteralPolicy.self,
            forKey: .integerLiteral
        )
        additionalInitializers =
            try values.decodeIfPresent(
                [IdentityInitializerOverride].self,
                forKey: .additionalInitializers
            ) ?? []
        documentation = try values.decodeIfPresent(
            IdentityDocumentationPolicy.self,
            forKey: .documentation
        )
        auditCategory = try values.decodeIfPresent(
            IdentityAuditCategory.self,
            forKey: .auditCategory
        )
    }

    var effectiveStorageName: String { storageName ?? "rawValue" }
    var effectiveConstructorLabel: String { constructorLabel ?? "rawValue" }
    var effectiveConstructorType: String { constructorType ?? rawType }
    var effectiveConstructorExpression: String { constructorExpression ?? constructorParameter }

    var directConformances: [String] {
        guard let sharedIDConformance, !sharedIDInExtension else { return conformances }
        return conformances + [sharedIDConformance]
    }

    var generatedExtensionConformances: [String] {
        var result = extensionConformances
        if let sharedIDConformance, sharedIDInExtension {
            result.insert(sharedIDConformance, at: 0)
        }
        return result
    }

    func validateDocumentation(failures: inout [String]) {
        guard access == .public else { return }
        requireDocumentation(documentation?.summary, label: "type", failures: &failures)
        if storageAccess == .public {
            requireDocumentation(documentation?.storage, label: "storage", failures: &failures)
        }
        if constructorAccess == .public {
            requireDocumentation(
                documentation?.constructor, label: "constructor", failures: &failures)
        }
        if description?.effectiveAccess(typeAccess: access) == .public {
            requireDocumentation(
                documentation?.description, label: "description", failures: &failures)
        }
        if let integerLiteral, integerLiteral.access == .public {
            requireDocumentation(
                documentation?.integerLiteral, label: "literal initializer", failures: &failures)
            if integerLiteral.typealiasAccess == .public {
                requireDocumentation(
                    documentation?.integerLiteralType, label: "literal type", failures: &failures)
            }
        }
    }

    func validateVisibility(failures: inout [String]) {
        guard access == .public, let auditCategory else { return }
        switch auditCategory {
        case .rawProtocolIdentity, .applicationIdentity, .opaqueProtocolToken:
            if storageAccess != .public {
                failures.append(
                    "\(type) is a \(auditCategory.rawValue) and needs public storage")
            }
            if constructorAccess != .public {
                failures.append(
                    "\(type) is a \(auditCategory.rawValue) and needs a public constructor")
            }

        case .clientIdentity, .publicProjection, .displayOwnedHandleIdentity,
            .seatScopedIdentity:
            if storageAccess == .public {
                failures.append(
                    "\(type) is a \(auditCategory.rawValue) and cannot expose public storage")
            }
            if constructorAccess == .public
                || additionalInitializers.contains(where: { $0.access == .public })
                || integerLiteral?.access == .public
            {
                failures.append(
                    "\(type) is a \(auditCategory.rawValue) and cannot expose public construction")
            }
        }
    }

    private func requireDocumentation(
        _ text: String?,
        label: String,
        failures: inout [String]
    ) {
        if text?.isEmpty != false {
            failures.append("\(type) has an undocumented public \(label)")
        }
    }
}
