enum ListenerBridgeHeaderRenderer {
    static func render(bridges: [ResolvedListenerBridge]) -> String {
        var lines = [
            "/* Generated by `swift run wck protocols generate`.",
            " * Sources: vendored Wayland XML and \(ListenerBridgeGeneration.policyPath).",
            " * Do not edit.",
            " */",
            "#ifndef WAYLAND_CLIENT_KIT_GENERATED_LISTENER_BRIDGES_H",
            "#define WAYLAND_CLIENT_KIT_GENERATED_LISTENER_BRIDGES_H",
            "",
            "#include <stdint.h>",
            "#include <wayland-client.h>",
            "",
        ]
        lines.append(contentsOf: renderForwardDeclarations(bridges: bridges))
        lines.append(contentsOf: [
            "",
            "#ifdef __cplusplus",
            "extern \"C\" {",
            "#endif",
            "",
        ])

        for (index, bridge) in bridges.enumerated() {
            if index > 0 {
                lines.append("")
            }
            lines.append(contentsOf: renderBridge(bridge))
        }

        lines.append(contentsOf: [
            "",
            "#ifdef __cplusplus",
            "}",
            "#endif",
            "",
            "#endif",
            "",
        ])
        return lines.joined(separator: "\n")
    }

    private static func renderForwardDeclarations(
        bridges: [ResolvedListenerBridge]
    ) -> [String] {
        var interfaceNames = Set(bridges.map(\.interface.name))
        for argument in bridges.flatMap(\.events).flatMap(\.arguments) {
            if let interfaceName = argument.interfaceName {
                interfaceNames.insert(interfaceName)
            }
        }
        return interfaceNames.sorted().map { "struct \($0);" }
    }

    private static func renderBridge(_ bridge: ResolvedListenerBridge) -> [String] {
        let callbackPrefix = bridge.policy.callbackPrefix
        var lines: [String] = []

        for (index, event) in bridge.events.enumerated() {
            if index > 0 {
                lines.append("")
            }
            lines.append(
                contentsOf: renderCallbackType(
                    interface: bridge.interface,
                    event: event,
                    callbackPrefix: callbackPrefix,
                    callbackName: bridge.policy.callbackName(for: event.name)
                ))
        }

        lines.append("")
        lines.append("struct swl_\(callbackPrefix)_listener_callbacks {")
        for event in bridge.events {
            let callbackName = bridge.policy.callbackName(for: event.name)
            lines.append(
                "    swl_\(callbackPrefix)_\(callbackName)_fn \(event.name);"
            )
        }
        lines.append("    void *data;")
        lines.append("};")
        lines.append("")
        lines.append("int swl_\(bridge.policy.effectiveInstallerPrefix)_add_listener(")
        lines.append("    struct \(bridge.interface.name) *object,")
        lines.append(
            "    const struct swl_\(callbackPrefix)_listener_callbacks *callbacks);"
        )
        return lines
    }

    private static func renderCallbackType(
        interface: WaylandInterfaceIR,
        event: WaylandMessageIR,
        callbackPrefix: String,
        callbackName: String
    ) -> [String] {
        var parameters = [
            "void *listener_data",
            ListenerBridgeC.declaration(
                type: ListenerBridgeC.pointerType(interfaceName: interface.name),
                name: "object"
            ),
        ]
        parameters.append(
            contentsOf: event.arguments.map { argument in
                ListenerBridgeC.declaration(
                    type: ListenerBridgeC.argumentType(argument),
                    name: ListenerBridgeC.argumentName(argument)
                )
            })

        var lines = ["typedef void (*swl_\(callbackPrefix)_\(callbackName)_fn)("]
        for (index, parameter) in parameters.enumerated() {
            let suffix = index == parameters.count - 1 ? ");" : ","
            lines.append("    \(parameter)\(suffix)")
        }
        return lines
    }
}
