enum ListenerBridgeSourceRenderer {
    static func render(bridges: [ResolvedListenerBridge]) -> String {
        let generatedBridges = bridges.filter { $0.policy.forwarding == .generated }
        let protocolHeaders = Set(generatedBridges.compactMap(\.generatedHeaderInclude)).sorted()
        var lines = [
            "/* Generated by `swift run wck protocols generate`.",
            " * Sources: vendored Wayland XML and \(ListenerBridgeGeneration.policyPath).",
            " * Do not edit.",
            " */",
            "#include \"generated/shims/listener-bridges.h\"",
        ]
        lines.append(contentsOf: protocolHeaders.map { "#include \"\($0)\"" })

        for bridge in generatedBridges {
            lines.append("")
            lines.append(contentsOf: renderBridge(bridge))
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }

    private static func renderBridge(_ bridge: ResolvedListenerBridge) -> [String] {
        var lines: [String] = []
        for (index, event) in bridge.events.enumerated() {
            if index > 0 {
                lines.append("")
            }
            lines.append(contentsOf: renderHandler(bridge: bridge, event: event))
        }
        lines.append("")
        lines.append(contentsOf: renderNativeListener(bridge))
        lines.append("")
        lines.append(contentsOf: renderInstaller(bridge))
        return lines
    }

    private static func renderHandler(
        bridge: ResolvedListenerBridge,
        event: WaylandMessageIR
    ) -> [String] {
        let callbackPrefix = bridge.policy.callbackPrefix
        var parameters = [
            "void *listener_data",
            ListenerBridgeC.declaration(
                type: ListenerBridgeC.pointerType(interfaceName: bridge.interface.name),
                name: "object"
            ),
        ]
        parameters.append(
            contentsOf: event.arguments.map { argument in
                ListenerBridgeC.declaration(
                    type: ListenerBridgeC.argumentType(argument),
                    name: ListenerBridgeC.argumentName(argument)
                )
            })

        var lines = ["static void swl_\(callbackPrefix)_handle_\(event.name)("]
        for (index, parameter) in parameters.enumerated() {
            let suffix = index == parameters.count - 1 ? ")" : ","
            lines.append("    \(parameter)\(suffix)")
        }
        lines.append("{")
        lines.append(
            "    const struct swl_\(callbackPrefix)_listener_callbacks *callbacks ="
        )
        lines.append("        listener_data;")
        lines.append("    if (callbacks && callbacks->\(event.name)) {")
        lines.append("        callbacks->\(event.name)(")

        let arguments =
            ["callbacks->data", "object"]
            + event.arguments.map(ListenerBridgeC.argumentName)
        for (index, argument) in arguments.enumerated() {
            let suffix = index == arguments.count - 1 ? ");" : ","
            lines.append("            \(argument)\(suffix)")
        }
        lines.append("    }")
        lines.append("}")
        return lines
    }

    private static func renderNativeListener(_ bridge: ResolvedListenerBridge) -> [String] {
        let callbackPrefix = bridge.policy.callbackPrefix
        var lines = [
            "static const struct \(bridge.interface.name)_listener",
            "    swl_\(callbackPrefix)_listener = {",
        ]
        for event in bridge.events {
            lines.append(
                "        .\(event.name) = swl_\(callbackPrefix)_handle_\(event.name),"
            )
        }
        lines.append("    };")
        return lines
    }

    private static func renderInstaller(_ bridge: ResolvedListenerBridge) -> [String] {
        let callbackPrefix = bridge.policy.callbackPrefix
        return [
            "int swl_\(bridge.policy.effectiveInstallerPrefix)_add_listener(",
            "    struct \(bridge.interface.name) *object,",
            "    const struct swl_\(callbackPrefix)_listener_callbacks *callbacks)",
            "{",
            "    return \(bridge.interface.name)_add_listener(",
            "        object,",
            "        &swl_\(callbackPrefix)_listener,",
            "        (void *)callbacks);",
            "}",
        ]
    }
}
