import Foundation

enum OptionalGlobalDescriptorsGeneration {
    static let outputPath =
        "Sources/WaylandRaw/Internal/Binding/OptionalGlobalDescriptors.swift"

    static func render(
        protocols: [WaylandProtocolIR],
        policy: WaylandProtocolGenerationPolicy
    ) throws -> String {
        try policy.validate(against: protocols)

        let optionalGlobals: [OptionalGlobalEntry] = try policy.interfaces.compactMap { entry in
            let (interfaceName, interfacePolicy) = entry
            guard interfacePolicy.globalBinding == .optional else { return nil }
            return OptionalGlobalEntry(
                interfaceName: interfaceName,
                descriptorName: try SupportedVersionsGeneration.swiftPropertyName(
                    for: interfaceName
                ),
                policy: interfacePolicy
            )
        }.sorted { lhs, rhs in lhs.interfaceName < rhs.interfaceName }
        let retainedGlobals = optionalGlobals.compactMap { entry in
            entry.policy.retainedOptionalGlobal.map { RetainedOptionalGlobalEntry(entry, $0) }
        }.sorted { $0.retainedPolicy.bindingOrder < $1.retainedPolicy.bindingOrder }

        return [
            header,
            renderDescriptorType(),
            renderDescriptorTable(optionalGlobals),
            renderOptionalGlobals(retainedGlobals),
            renderBinding(retainedGlobals),
        ].joined(separator: "\n")
    }

    private static let header = """
        // Generated by `swift run wck protocols generate`.
        // Sources: vendored Wayland XML and protocols/generation-policy.json.
        // Do not edit.
        // swiftlint:disable file_length

        """

    private static func renderDescriptorType() -> String {
        """
        package enum OptionalGlobalBindingDecision: Equatable, Sendable {
            case unsupportedVersion(advertised: RawVersion, minimum: RawVersion)
            case bind(version: RawVersion)
        }

        package struct OptionalGlobalDescriptor: Equatable, Sendable {
            package let interfaceName: String
            package let maximumSupportedVersion: RawVersion
            package let minimumRequiredVersion: RawVersion?
            package let reportsCapability: Bool

            package var minimumBindableVersion: RawVersion {
                minimumRequiredVersion ?? 1
            }

            package func negotiatedVersion(
                for global: RawGlobalAdvertisement
            ) -> RawVersion {
                global.negotiatedVersion(supportedByClient: maximumSupportedVersion)
            }

            package func bindingDecision(
                for global: RawGlobalAdvertisement
            ) -> OptionalGlobalBindingDecision {
                guard global.advertisedVersion >= minimumBindableVersion else {
                    return .unsupportedVersion(
                        advertised: global.advertisedVersion,
                        minimum: minimumBindableVersion
                    )
                }
                return .bind(version: negotiatedVersion(for: global))
            }
        }

        """
    }

    private static func renderDescriptorTable(_ entries: [OptionalGlobalEntry]) -> String {
        let declarations = entries.map { entry in
            let minimumVersion: String
            if entry.policy.minimumRequiredVersion == nil {
                minimumVersion = "nil"
            } else {
                minimumVersion = "SupportedVersions.\(entry.descriptorName)Minimum"
            }
            return """
                    package static let \(entry.descriptorName) = OptionalGlobalDescriptor(
                        interfaceName: "\(entry.interfaceName)",
                        maximumSupportedVersion: SupportedVersions.\(entry.descriptorName),
                        minimumRequiredVersion: \(minimumVersion),
                        reportsCapability: \(entry.policy.reportsCapability)
                    )
                """
        }.joined(separator: "\n\n")
        let allEntries = entries.map { entry in
            "        \(entry.descriptorName),"
        }.joined(separator: "\n")
        let capabilityEntries = entries.filter { entry in
            entry.policy.reportsCapability
        }.map { entry in
            "        \(entry.descriptorName).interfaceName,"
        }.joined(separator: "\n")

        return """
            // swiftlint:disable:next type_body_length
            package enum OptionalGlobalDescriptors {
            \(declarations)

                package static let all: [OptionalGlobalDescriptor] = [
            \(allEntries)
                ]

                package static let capabilityInterfaceNames: [String] = [
            \(capabilityEntries)
                ]
            }

            """
    }

    private static func renderBinding(_ entries: [RetainedOptionalGlobalEntry]) -> String {
        let bindingDeclaration =
            "    package func bindOptionalGlobals(registry reg: OpaquePointer) "
            + "throws -> OptionalGlobals"
        let acquisitions = entries.map { entry in
            let binding =
                "let \(entry.propertyName) = try \(entry.bindingMethodName)(registry: reg)"
            let formattedBinding: String
            if binding.count + 8 > 100 {
                formattedBinding =
                    "        let \(entry.propertyName) = try \(entry.bindingMethodName)(\n"
                    + "            registry: reg)"
            } else {
                formattedBinding = "        " + binding
            }
            return formattedBinding
                + "\n        rollback.append { \(entry.propertyName).destroy() }"
        }.joined(separator: "\n")
        let initializerArguments = entries.map { entry in
            "            \(entry.propertyName): \(entry.propertyName),"
        }.joined(separator: "\n")

        return """
            extension RawDisplayConnection {
                // swiftlint:disable function_body_length
                @safe
            \(bindingDeclaration) {
                    let rollback = OptionalGlobalRollback()

            \(acquisitions)

                    rollback.disarm()
                    return OptionalGlobals(
            \(initializerArguments)
                    )
                }
                // swiftlint:enable function_body_length
            }

            """
    }

    private static func renderOptionalGlobals(
        _ entries: [RetainedOptionalGlobalEntry]
    ) -> String {
        let properties = entries.map { entry in
            "    package private(set) var \(entry.propertyName): \(entry.wrapperTypeName)"
        }.joined(separator: "\n")
        let initializerParameters = entries.map { entry in
            "        \(entry.propertyName): \(entry.wrapperTypeName) = .missing,"
        }.joined(separator: "\n")
        let assignments = entries.map { entry in
            "        self.\(entry.propertyName) = \(entry.propertyName)"
        }.joined(separator: "\n")
        let destruction = entries.reversed().map { entry in
            "        \(entry.propertyName).destroy()"
        }.joined(separator: "\n")
        let invalidation = entries.map { entry in
            """
                    case "\(entry.interfaceName)":
                        retireOptionalGlobal(&\(entry.propertyName))
            """
        }.joined(separator: "\n")

        return """
            package final class OptionalGlobals {
            \(properties)

                package init(
            \(initializerParameters)
                ) {
            \(assignments)
                }

                func destroy() {
            \(destruction)
                }

                // swiftlint:disable:next cyclomatic_complexity
                package func invalidate(named interfaceName: String) {
                    switch interfaceName {
            \(invalidation)
                    default:
                        break
                    }
                }
            }

            """
    }
}

private struct OptionalGlobalEntry {
    let interfaceName: String
    let descriptorName: String
    let policy: WaylandInterfaceGenerationPolicy
}

private struct RetainedOptionalGlobalEntry {
    let optionalGlobal: OptionalGlobalEntry
    let retainedPolicy: WaylandRetainedOptionalGlobalPolicy

    init(
        _ optionalGlobalEntry: OptionalGlobalEntry,
        _ retainedOptionalGlobalPolicy: WaylandRetainedOptionalGlobalPolicy
    ) {
        optionalGlobal = optionalGlobalEntry
        retainedPolicy = retainedOptionalGlobalPolicy
    }

    var interfaceName: String { optionalGlobal.interfaceName }
    var propertyName: String { retainedPolicy.propertyName }
    var bindingMethodName: String { retainedPolicy.bindingMethodName }
    var wrapperTypeName: String { retainedPolicy.wrapperTypeName }
}

extension ProtocolTooling {
    /// Renders optional-global descriptors and ownership orchestration from XML and policy.
    public func renderOptionalGlobalDescriptors() throws -> String {
        try OptionalGlobalDescriptorsGeneration.render(
            protocols: loadProtocolIRs(),
            policy: loadGenerationPolicy()
        )
    }

    func renderOptionalGlobalDescriptors(protocols: [WaylandProtocolIR]) throws -> String {
        try OptionalGlobalDescriptorsGeneration.render(
            protocols: protocols,
            policy: loadGenerationPolicy()
        )
    }

    func writeOptionalGlobalDescriptors(_ text: String, outputRoot: URL) throws {
        let output = outputRoot.appendingPathComponent(
            OptionalGlobalDescriptorsGeneration.outputPath
        )
        try fileSystem.createDirectory(output.deletingLastPathComponent())
        try fileSystem.writeText(text, to: output)
    }
}
