enum RegistryBindBridgeHeaderRenderer {
    static func render(bridges: [ResolvedRegistryBindBridge]) -> String {
        var lines = [
            "/* Generated by `swift run wck protocols generate`.",
            " * Sources: vendored Wayland XML and \(SupportedVersionsGeneration.policyPath).",
            " * Do not edit.",
            " */",
            "#ifndef WAYLAND_CLIENT_KIT_GENERATED_REGISTRY_BIND_BRIDGES_H",
            "#define WAYLAND_CLIENT_KIT_GENERATED_REGISTRY_BIND_BRIDGES_H",
            "",
            "#include <stdint.h>",
            "#include <wayland-client.h>",
            "",
        ]
        lines.append(contentsOf: bridges.map { "struct \($0.interface.name);" })
        lines.append(contentsOf: [
            "",
            "#ifdef __cplusplus",
            "extern \"C\" {",
            "#endif",
        ])

        for bridge in bridges {
            lines.append("")
            lines.append(contentsOf: renderDeclaration(bridge))
        }

        lines.append(contentsOf: [
            "",
            "#ifdef __cplusplus",
            "}",
            "#endif",
            "",
            "#endif",
            "",
        ])
        return lines.joined(separator: "\n")
    }

    private static func renderDeclaration(_ bridge: ResolvedRegistryBindBridge) -> [String] {
        [
            "struct \(bridge.interface.name) *\(bridge.functionName)(",
            "    struct wl_registry *registry, uint32_t name, uint32_t version);",
        ]
    }
}
