enum RegistryBindBridgeSourceRenderer {
    static func render(bridges: [ResolvedRegistryBindBridge]) -> String {
        let protocolHeaders = Set(bridges.compactMap(\.generatedHeaderInclude)).sorted()
        var lines = [
            "/* Generated by `swift run wck protocols generate`.",
            " * Sources: vendored Wayland XML and \(SupportedVersionsGeneration.policyPath).",
            " * Do not edit.",
            " */",
            "#include \"generated/shims/registry-bind-bridges.h\"",
        ]
        lines.append(contentsOf: protocolHeaders.map { "#include \"\($0)\"" })

        for bridge in bridges {
            lines.append("")
            lines.append(contentsOf: renderBridge(bridge))
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }

    private static func renderBridge(_ bridge: ResolvedRegistryBindBridge) -> [String] {
        let interfaceName = bridge.interface.name
        return [
            "struct \(interfaceName) *\(bridge.functionName)(",
            "    struct wl_registry *registry, uint32_t name, uint32_t version)",
            "{",
            "    return (struct \(interfaceName) *)wl_registry_bind(",
            "        registry, name, &\(interfaceName)_interface, version);",
            "}",
        ]
    }
}
