enum RequestBridgeSourceRenderer {
    static func render(bridges: [ResolvedRequestBridge]) -> String {
        let protocolHeaders = Set(bridges.compactMap(\.generatedHeaderInclude)).sorted()
        var lines = [
            "/* Generated by `swift run wck protocols generate`.",
            " * Sources: vendored Wayland XML and \(RequestBridgeGeneration.policyPath).",
            " * Do not edit.",
            " */",
            "#include \"generated/shims/request-bridges.h\"",
        ]
        lines.append(contentsOf: protocolHeaders.map { "#include \"\($0)\"" })

        for bridge in bridges {
            lines.append("")
            lines.append(contentsOf: renderBridge(bridge))
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }

    private static func renderBridge(_ bridge: ResolvedRequestBridge) -> [String] {
        let returnType = RequestBridgeC.returnType(for: bridge.request)
        let parameters = RequestBridgeC.parameterDeclarations(for: bridge)
        var lines = [
            ListenerBridgeC.declaration(
                type: returnType,
                name: bridge.functionName
            ) + "("
        ]
        for (index, parameter) in parameters.enumerated() {
            let suffix = index == parameters.count - 1 ? ")" : ","
            lines.append("    \(parameter)\(suffix)")
        }
        lines.append("{")

        let nativeFunction = "\(bridge.interface.name)_\(bridge.request.name)"
        let callPrefix = returnType == "void" ? "    " : "    return "
        let arguments = RequestBridgeC.callArguments(for: bridge)
        if arguments.count == 1 {
            lines.append("\(callPrefix)\(nativeFunction)(\(arguments[0]));")
        } else {
            lines.append("\(callPrefix)\(nativeFunction)(")
            for (index, argument) in arguments.enumerated() {
                let suffix = index == arguments.count - 1 ? ");" : ","
                lines.append("        \(argument)\(suffix)")
            }
        }
        lines.append("}")
        return lines
    }
}
