enum RequestBridgeHeaderRenderer {
    static func render(bridges: [ResolvedRequestBridge]) -> String {
        var lines = [
            "/* Generated by `swift run wck protocols generate`.",
            " * Sources: vendored Wayland XML and \(RequestBridgeGeneration.policyPath).",
            " * Do not edit.",
            " */",
            "#ifndef WAYLAND_CLIENT_KIT_GENERATED_REQUEST_BRIDGES_H",
            "#define WAYLAND_CLIENT_KIT_GENERATED_REQUEST_BRIDGES_H",
            "",
            "#include <stdint.h>",
            "#include <wayland-client.h>",
            "",
        ]
        lines.append(contentsOf: renderForwardDeclarations(bridges: bridges))
        lines.append(contentsOf: [
            "",
            "#ifdef __cplusplus",
            "extern \"C\" {",
            "#endif",
        ])

        for bridge in bridges {
            lines.append("")
            lines.append(contentsOf: renderDeclaration(bridge))
        }

        lines.append(contentsOf: [
            "",
            "#ifdef __cplusplus",
            "}",
            "#endif",
            "",
            "#endif",
            "",
        ])
        return lines.joined(separator: "\n")
    }

    private static func renderForwardDeclarations(
        bridges: [ResolvedRequestBridge]
    ) -> [String] {
        var interfaceNames = Set(bridges.map(\.interface.name))
        for argument in bridges.flatMap(\.request.arguments) {
            if let interfaceName = argument.interfaceName {
                interfaceNames.insert(interfaceName)
            }
        }
        return interfaceNames.sorted().map { "struct \($0);" }
    }

    private static func renderDeclaration(_ bridge: ResolvedRequestBridge) -> [String] {
        let returnType = RequestBridgeC.returnType(for: bridge.request)
        let parameters = RequestBridgeC.parameterDeclarations(for: bridge)
        var lines = [
            ListenerBridgeC.declaration(
                type: returnType,
                name: bridge.functionName
            ) + "("
        ]
        for (index, parameter) in parameters.enumerated() {
            let suffix = index == parameters.count - 1 ? ");" : ","
            lines.append("    \(parameter)\(suffix)")
        }
        return lines
    }
}
