import Foundation

enum SupportedVersionsGeneration {
    static let policyPath = "protocols/generation-policy.json"
    static let outputPath = "Sources/WaylandRaw/Internal/Binding/SupportedVersions.swift"

    static func render(
        protocols: [WaylandProtocolIR],
        policy: WaylandProtocolGenerationPolicy
    ) throws -> String {
        try policy.validate(against: protocols)

        var declarations: [String] = []
        var propertyNames: Set<String> = []
        for interfaceName in policy.interfaces.keys.sorted() {
            guard let interfacePolicy = policy.interfaces[interfaceName] else { continue }
            let propertyName = try swiftPropertyName(for: interfaceName)
            guard propertyNames.insert(propertyName).inserted else {
                throw ToolError(
                    "protocol generation policy produces duplicate Swift name: \(propertyName)",
                    exitCode: ToolExitCode.data
                )
            }

            if let minimumVersion = interfacePolicy.minimumRequiredVersion {
                declarations.append(
                    "    package static let \(propertyName)Minimum: RawVersion = \(minimumVersion)"
                )
            }
            declarations.append(
                "    package static let \(propertyName): RawVersion = "
                    + "\(interfacePolicy.maximumSupportedVersion)"
            )
        }

        return [
            "// Generated by `swift run wck protocols generate`.",
            "// Sources: vendored Wayland XML and \(policyPath).",
            "// Do not edit.",
            "",
            "package enum SupportedVersions {",
            declarations.joined(separator: "\n"),
            "}",
            "",
        ].joined(separator: "\n")
    }

    private static func swiftPropertyName(for interfaceName: String) throws -> String {
        let components = interfaceName.split(
            separator: "_",
            omittingEmptySubsequences: false
        )
        guard let first = components.first, !first.isEmpty,
            components.allSatisfy({ !$0.isEmpty })
        else {
            throw invalidInterfaceName(interfaceName)
        }

        let propertyName =
            String(first)
            + components.dropFirst().map { component in
                component.prefix(1).uppercased() + String(component.dropFirst())
            }.joined()
        guard propertyName.first?.isLetter == true,
            propertyName.allSatisfy({ $0.isLetter || $0.isNumber })
        else {
            throw invalidInterfaceName(interfaceName)
        }
        return propertyName
    }

    private static func invalidInterfaceName(_ interfaceName: String) -> ToolError {
        ToolError(
            "protocol generation policy cannot form a Swift name from: \(interfaceName)",
            exitCode: ToolExitCode.data
        )
    }
}

extension ProtocolTooling {
    /// Loads client-specific protocol generation choices.
    public func loadGenerationPolicy() throws -> WaylandProtocolGenerationPolicy {
        try JSONHelpers.decode(
            WaylandProtocolGenerationPolicy.self,
            from: repository.url(SupportedVersionsGeneration.policyPath)
        )
    }

    /// Renders the checked-in supported-version declarations from XML and client policy.
    public func renderSupportedVersions() throws -> String {
        try SupportedVersionsGeneration.render(
            protocols: loadProtocolIRs(),
            policy: loadGenerationPolicy()
        )
    }

    func renderSupportedVersions(protocols: [WaylandProtocolIR]) throws -> String {
        try SupportedVersionsGeneration.render(
            protocols: protocols,
            policy: loadGenerationPolicy()
        )
    }

    func writeSupportedVersions(_ text: String, outputRoot: URL) throws {
        let output = outputRoot.appendingPathComponent(SupportedVersionsGeneration.outputPath)
        try fileSystem.createDirectory(output.deletingLastPathComponent())
        try fileSystem.writeText(text, to: output)
    }
}
