#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PROTO_DIR="$ROOT/protocols/upstream"
OUT_DIR="$ROOT/Sources/CWaylandProtocols"
GEN_INC="$OUT_DIR/include/generated"
GEN_SRC="$OUT_DIR/generated"

command -v wayland-scanner >/dev/null 2>&1 || {
    echo "wayland-scanner not found on PATH"
    exit 1
}

[[ -f "$PROTO_DIR/core/wayland.xml" ]] || {
    echo "Missing vendored protocol: $PROTO_DIR/core/wayland.xml"
    exit 1
}

[[ -f "$PROTO_DIR/stable/xdg-shell/xdg-shell.xml" ]] || {
    echo "Missing vendored protocol: $PROTO_DIR/stable/xdg-shell/xdg-shell.xml"
    exit 1
}

[[ -f "$PROTO_DIR/legacy-unstable/xdg-decoration/xdg-decoration-unstable-v1.xml" ]] || {
    echo "Missing vendored protocol: $PROTO_DIR/legacy-unstable/xdg-decoration/xdg-decoration-unstable-v1.xml"
    exit 1
}

[[ -f "$PROTO_DIR/legacy-unstable/xdg-output/xdg-output-unstable-v1.xml" ]] || {
    echo "Missing vendored protocol: $PROTO_DIR/legacy-unstable/xdg-output/xdg-output-unstable-v1.xml"
    exit 1
}

[[ -f "$PROTO_DIR/stable/viewporter/viewporter.xml" ]] || {
    echo "Missing vendored protocol: $PROTO_DIR/stable/viewporter/viewporter.xml"
    exit 1
}

[[ -f "$PROTO_DIR/stable/presentation-time/presentation-time.xml" ]] || {
    echo "Missing vendored protocol: $PROTO_DIR/stable/presentation-time/presentation-time.xml"
    exit 1
}

[[ -f "$PROTO_DIR/staging/fractional-scale/fractional-scale-v1.xml" ]] || {
    echo "Missing vendored protocol: $PROTO_DIR/staging/fractional-scale/fractional-scale-v1.xml"
    exit 1
}

[[ -f "$PROTO_DIR/legacy-unstable/primary-selection/primary-selection-unstable-v1.xml" ]] || {
    echo "Missing vendored protocol: $PROTO_DIR/legacy-unstable/primary-selection/primary-selection-unstable-v1.xml"
    exit 1
}

rm -rf "$GEN_INC" "$GEN_SRC"
mkdir -p \
    "$GEN_INC/core" \
    "$GEN_INC/stable/xdg-shell" \
    "$GEN_INC/stable/viewporter" \
    "$GEN_INC/stable/presentation-time" \
    "$GEN_INC/staging/fractional-scale" \
    "$GEN_INC/legacy-unstable/xdg-decoration" \
    "$GEN_INC/legacy-unstable/xdg-output" \
    "$GEN_INC/legacy-unstable/primary-selection" \
    "$GEN_SRC/core" \
    "$GEN_SRC/stable/xdg-shell" \
    "$GEN_SRC/stable/viewporter" \
    "$GEN_SRC/stable/presentation-time" \
    "$GEN_SRC/staging/fractional-scale" \
    "$GEN_SRC/legacy-unstable/xdg-decoration" \
    "$GEN_SRC/legacy-unstable/xdg-output" \
    "$GEN_SRC/legacy-unstable/primary-selection" \
    "$OUT_DIR/shims"

normalize_generated_file() {
    local generated_file="$1"

    sed -i -E \
        -e 's/[[:space:]]+$//' \
        -e '1s@/\* Generated by wayland-scanner [^*]+ \*/@/* Generated by wayland-scanner */@' \
        -e '/^#include <stdbool\.h>$/d' \
        -e '/^[[:space:]]+\* @deprecated Deprecated since version [0-9]+$/d' \
        "$generated_file"

    awk '
        { lines[NR] = $0 }
        END {
            last = NR
            while (last > 0 && lines[last] == "") {
                last--
            }
            for (line = 1; line <= last; line++) {
                print lines[line]
            }
        }
    ' "$generated_file" >"$generated_file.tmp"
    mv "$generated_file.tmp" "$generated_file"
}

wayland-scanner client-header \
    "$PROTO_DIR/core/wayland.xml" \
    "$GEN_INC/core/wayland-client-protocol.h"

wayland-scanner private-code \
    "$PROTO_DIR/core/wayland.xml" \
    "$GEN_SRC/core/wayland-protocol.c"

wayland-scanner client-header \
    "$PROTO_DIR/stable/xdg-shell/xdg-shell.xml" \
    "$GEN_INC/stable/xdg-shell/xdg-shell-client-protocol.h"

wayland-scanner private-code \
    "$PROTO_DIR/stable/xdg-shell/xdg-shell.xml" \
    "$GEN_SRC/stable/xdg-shell/xdg-shell-protocol.c"

wayland-scanner client-header \
    "$PROTO_DIR/legacy-unstable/xdg-decoration/xdg-decoration-unstable-v1.xml" \
    "$GEN_INC/legacy-unstable/xdg-decoration/xdg-decoration-unstable-v1-client-protocol.h"

wayland-scanner private-code \
    "$PROTO_DIR/legacy-unstable/xdg-decoration/xdg-decoration-unstable-v1.xml" \
    "$GEN_SRC/legacy-unstable/xdg-decoration/xdg-decoration-unstable-v1-protocol.c"

wayland-scanner client-header \
    "$PROTO_DIR/legacy-unstable/xdg-output/xdg-output-unstable-v1.xml" \
    "$GEN_INC/legacy-unstable/xdg-output/xdg-output-unstable-v1-client-protocol.h"

wayland-scanner private-code \
    "$PROTO_DIR/legacy-unstable/xdg-output/xdg-output-unstable-v1.xml" \
    "$GEN_SRC/legacy-unstable/xdg-output/xdg-output-unstable-v1-protocol.c"

wayland-scanner client-header \
    "$PROTO_DIR/stable/viewporter/viewporter.xml" \
    "$GEN_INC/stable/viewporter/viewporter-client-protocol.h"

wayland-scanner private-code \
    "$PROTO_DIR/stable/viewporter/viewporter.xml" \
    "$GEN_SRC/stable/viewporter/viewporter-protocol.c"

wayland-scanner client-header \
    "$PROTO_DIR/stable/presentation-time/presentation-time.xml" \
    "$GEN_INC/stable/presentation-time/presentation-time-client-protocol.h"

wayland-scanner private-code \
    "$PROTO_DIR/stable/presentation-time/presentation-time.xml" \
    "$GEN_SRC/stable/presentation-time/presentation-time-protocol.c"

wayland-scanner client-header \
    "$PROTO_DIR/staging/fractional-scale/fractional-scale-v1.xml" \
    "$GEN_INC/staging/fractional-scale/fractional-scale-v1-client-protocol.h"

wayland-scanner private-code \
    "$PROTO_DIR/staging/fractional-scale/fractional-scale-v1.xml" \
    "$GEN_SRC/staging/fractional-scale/fractional-scale-v1-protocol.c"

wayland-scanner client-header \
    "$PROTO_DIR/legacy-unstable/primary-selection/primary-selection-unstable-v1.xml" \
    "$GEN_INC/legacy-unstable/primary-selection/primary-selection-unstable-v1-client-protocol.h"

wayland-scanner private-code \
    "$PROTO_DIR/legacy-unstable/primary-selection/primary-selection-unstable-v1.xml" \
    "$GEN_SRC/legacy-unstable/primary-selection/primary-selection-unstable-v1-protocol.c"

while IFS= read -r generated_file; do
    normalize_generated_file "$generated_file"
done < <(find "$GEN_INC" "$GEN_SRC" -type f \( -name '*.h' -o -name '*.c' \) | sort)

echo "Generated Wayland protocol artifacts in $OUT_DIR"
