// Generated by `swift run wck protocols generate`.
// Sources: vendored Wayland XML and protocols/generation-policy.json.
// Do not edit.
// swiftlint:disable file_length

package enum OptionalGlobalBindingDecision: Equatable, Sendable {
    case unsupportedVersion(advertised: RawVersion, minimum: RawVersion)
    case bind(version: RawVersion)
}

package struct OptionalGlobalDescriptor: Equatable, Sendable {
    package let interfaceName: String
    package let maximumSupportedVersion: RawVersion
    package let minimumRequiredVersion: RawVersion?
    package let reportsCapability: Bool

    package var minimumBindableVersion: RawVersion {
        minimumRequiredVersion ?? 1
    }

    package func negotiatedVersion(
        for global: RawGlobalAdvertisement
    ) -> RawVersion {
        global.negotiatedVersion(supportedByClient: maximumSupportedVersion)
    }

    package func bindingDecision(
        for global: RawGlobalAdvertisement
    ) -> OptionalGlobalBindingDecision {
        guard global.advertisedVersion >= minimumBindableVersion else {
            return .unsupportedVersion(
                advertised: global.advertisedVersion,
                minimum: minimumBindableVersion
            )
        }
        return .bind(version: negotiatedVersion(for: global))
    }
}

// swiftlint:disable:next type_body_length
package enum OptionalGlobalDescriptors {
    package static let extForeignToplevelListV1 = OptionalGlobalDescriptor(
        interfaceName: "ext_foreign_toplevel_list_v1",
        maximumSupportedVersion: SupportedVersions.extForeignToplevelListV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let wlDataDeviceManager = OptionalGlobalDescriptor(
        interfaceName: "wl_data_device_manager",
        maximumSupportedVersion: SupportedVersions.wlDataDeviceManager,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let wlOutput = OptionalGlobalDescriptor(
        interfaceName: "wl_output",
        maximumSupportedVersion: SupportedVersions.wlOutput,
        minimumRequiredVersion: nil,
        reportsCapability: false
    )

    package static let wlSeat = OptionalGlobalDescriptor(
        interfaceName: "wl_seat",
        maximumSupportedVersion: SupportedVersions.wlSeat,
        minimumRequiredVersion: SupportedVersions.wlSeatMinimum,
        reportsCapability: false
    )

    package static let wlSubcompositor = OptionalGlobalDescriptor(
        interfaceName: "wl_subcompositor",
        maximumSupportedVersion: SupportedVersions.wlSubcompositor,
        minimumRequiredVersion: nil,
        reportsCapability: false
    )

    package static let wpAlphaModifierV1 = OptionalGlobalDescriptor(
        interfaceName: "wp_alpha_modifier_v1",
        maximumSupportedVersion: SupportedVersions.wpAlphaModifierV1,
        minimumRequiredVersion: nil,
        reportsCapability: false
    )

    package static let wpColorManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "wp_color_manager_v1",
        maximumSupportedVersion: SupportedVersions.wpColorManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: false
    )

    package static let wpColorRepresentationManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "wp_color_representation_manager_v1",
        maximumSupportedVersion: SupportedVersions.wpColorRepresentationManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: false
    )

    package static let wpCommitTimingManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "wp_commit_timing_manager_v1",
        maximumSupportedVersion: SupportedVersions.wpCommitTimingManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: false
    )

    package static let wpContentTypeManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "wp_content_type_manager_v1",
        maximumSupportedVersion: SupportedVersions.wpContentTypeManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: false
    )

    package static let wpCursorShapeManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "wp_cursor_shape_manager_v1",
        maximumSupportedVersion: SupportedVersions.wpCursorShapeManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let wpFifoManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "wp_fifo_manager_v1",
        maximumSupportedVersion: SupportedVersions.wpFifoManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: false
    )

    package static let wpFractionalScaleManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "wp_fractional_scale_manager_v1",
        maximumSupportedVersion: SupportedVersions.wpFractionalScaleManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let wpLinuxDrmSyncobjManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "wp_linux_drm_syncobj_manager_v1",
        maximumSupportedVersion: SupportedVersions.wpLinuxDrmSyncobjManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: false
    )

    package static let wpPointerWarpV1 = OptionalGlobalDescriptor(
        interfaceName: "wp_pointer_warp_v1",
        maximumSupportedVersion: SupportedVersions.wpPointerWarpV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let wpPresentation = OptionalGlobalDescriptor(
        interfaceName: "wp_presentation",
        maximumSupportedVersion: SupportedVersions.wpPresentation,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let wpTearingControlManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "wp_tearing_control_manager_v1",
        maximumSupportedVersion: SupportedVersions.wpTearingControlManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: false
    )

    package static let wpViewporter = OptionalGlobalDescriptor(
        interfaceName: "wp_viewporter",
        maximumSupportedVersion: SupportedVersions.wpViewporter,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let xdgActivationV1 = OptionalGlobalDescriptor(
        interfaceName: "xdg_activation_v1",
        maximumSupportedVersion: SupportedVersions.xdgActivationV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let xdgSessionManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "xdg_session_manager_v1",
        maximumSupportedVersion: SupportedVersions.xdgSessionManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let xdgSystemBellV1 = OptionalGlobalDescriptor(
        interfaceName: "xdg_system_bell_v1",
        maximumSupportedVersion: SupportedVersions.xdgSystemBellV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let xdgToplevelDragManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "xdg_toplevel_drag_manager_v1",
        maximumSupportedVersion: SupportedVersions.xdgToplevelDragManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let xdgToplevelIconManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "xdg_toplevel_icon_manager_v1",
        maximumSupportedVersion: SupportedVersions.xdgToplevelIconManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let xdgWmDialogV1 = OptionalGlobalDescriptor(
        interfaceName: "xdg_wm_dialog_v1",
        maximumSupportedVersion: SupportedVersions.xdgWmDialogV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let zwlrOutputManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "zwlr_output_manager_v1",
        maximumSupportedVersion: SupportedVersions.zwlrOutputManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let zwpIdleInhibitManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "zwp_idle_inhibit_manager_v1",
        maximumSupportedVersion: SupportedVersions.zwpIdleInhibitManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let zwpKeyboardShortcutsInhibitManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "zwp_keyboard_shortcuts_inhibit_manager_v1",
        maximumSupportedVersion: SupportedVersions.zwpKeyboardShortcutsInhibitManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let zwpLinuxDmabufV1 = OptionalGlobalDescriptor(
        interfaceName: "zwp_linux_dmabuf_v1",
        maximumSupportedVersion: SupportedVersions.zwpLinuxDmabufV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let zwpPointerConstraintsV1 = OptionalGlobalDescriptor(
        interfaceName: "zwp_pointer_constraints_v1",
        maximumSupportedVersion: SupportedVersions.zwpPointerConstraintsV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let zwpPointerGesturesV1 = OptionalGlobalDescriptor(
        interfaceName: "zwp_pointer_gestures_v1",
        maximumSupportedVersion: SupportedVersions.zwpPointerGesturesV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let zwpPrimarySelectionDeviceManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "zwp_primary_selection_device_manager_v1",
        maximumSupportedVersion: SupportedVersions.zwpPrimarySelectionDeviceManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let zwpRelativePointerManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "zwp_relative_pointer_manager_v1",
        maximumSupportedVersion: SupportedVersions.zwpRelativePointerManagerV1,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let zwpTabletManagerV2 = OptionalGlobalDescriptor(
        interfaceName: "zwp_tablet_manager_v2",
        maximumSupportedVersion: SupportedVersions.zwpTabletManagerV2,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let zwpTextInputManagerV3 = OptionalGlobalDescriptor(
        interfaceName: "zwp_text_input_manager_v3",
        maximumSupportedVersion: SupportedVersions.zwpTextInputManagerV3,
        minimumRequiredVersion: nil,
        reportsCapability: true
    )

    package static let zxdgDecorationManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "zxdg_decoration_manager_v1",
        maximumSupportedVersion: SupportedVersions.zxdgDecorationManagerV1,
        minimumRequiredVersion: SupportedVersions.zxdgDecorationManagerV1Minimum,
        reportsCapability: true
    )

    package static let zxdgOutputManagerV1 = OptionalGlobalDescriptor(
        interfaceName: "zxdg_output_manager_v1",
        maximumSupportedVersion: SupportedVersions.zxdgOutputManagerV1,
        minimumRequiredVersion: SupportedVersions.zxdgOutputManagerV1Minimum,
        reportsCapability: true
    )

    package static let all: [OptionalGlobalDescriptor] = [
        extForeignToplevelListV1,
        wlDataDeviceManager,
        wlOutput,
        wlSeat,
        wlSubcompositor,
        wpAlphaModifierV1,
        wpColorManagerV1,
        wpColorRepresentationManagerV1,
        wpCommitTimingManagerV1,
        wpContentTypeManagerV1,
        wpCursorShapeManagerV1,
        wpFifoManagerV1,
        wpFractionalScaleManagerV1,
        wpLinuxDrmSyncobjManagerV1,
        wpPointerWarpV1,
        wpPresentation,
        wpTearingControlManagerV1,
        wpViewporter,
        xdgActivationV1,
        xdgSessionManagerV1,
        xdgSystemBellV1,
        xdgToplevelDragManagerV1,
        xdgToplevelIconManagerV1,
        xdgWmDialogV1,
        zwlrOutputManagerV1,
        zwpIdleInhibitManagerV1,
        zwpKeyboardShortcutsInhibitManagerV1,
        zwpLinuxDmabufV1,
        zwpPointerConstraintsV1,
        zwpPointerGesturesV1,
        zwpPrimarySelectionDeviceManagerV1,
        zwpRelativePointerManagerV1,
        zwpTabletManagerV2,
        zwpTextInputManagerV3,
        zxdgDecorationManagerV1,
        zxdgOutputManagerV1,
    ]

    package static let capabilityInterfaceNames: [String] = [
        extForeignToplevelListV1.interfaceName,
        wlDataDeviceManager.interfaceName,
        wpCursorShapeManagerV1.interfaceName,
        wpFractionalScaleManagerV1.interfaceName,
        wpPointerWarpV1.interfaceName,
        wpPresentation.interfaceName,
        wpViewporter.interfaceName,
        xdgActivationV1.interfaceName,
        xdgSessionManagerV1.interfaceName,
        xdgSystemBellV1.interfaceName,
        xdgToplevelDragManagerV1.interfaceName,
        xdgToplevelIconManagerV1.interfaceName,
        xdgWmDialogV1.interfaceName,
        zwlrOutputManagerV1.interfaceName,
        zwpIdleInhibitManagerV1.interfaceName,
        zwpKeyboardShortcutsInhibitManagerV1.interfaceName,
        zwpLinuxDmabufV1.interfaceName,
        zwpPointerConstraintsV1.interfaceName,
        zwpPointerGesturesV1.interfaceName,
        zwpPrimarySelectionDeviceManagerV1.interfaceName,
        zwpRelativePointerManagerV1.interfaceName,
        zwpTabletManagerV2.interfaceName,
        zwpTextInputManagerV3.interfaceName,
        zxdgDecorationManagerV1.interfaceName,
        zxdgOutputManagerV1.interfaceName,
    ]
}

package final class OptionalGlobals {
    package private(set) var xdgDecorationManager: OptionalXDGDecorationManager
    package private(set) var xdgOutputManager: OptionalXDGOutputManager
    package private(set) var viewporter: OptionalViewporter
    package private(set) var presentation: OptionalPresentation
    package private(set) var fractionalScaleManager: OptionalFractionalScaleManager
    package private(set) var cursorShapeManager: OptionalCursorShapeManager
    package private(set) var dataDeviceManager: OptionalDataDeviceManager
    package private(set) var primarySelectionDeviceManager: OptionalPrimarySelectionDeviceManager
    package private(set) var textInputManager: OptionalTextInputManager
    package private(set) var linuxDmabuf: OptionalLinuxDmabuf
    package private(set) var linuxDrmSyncobjManager: OptionalLinuxDrmSyncobjManager
    package private(set) var fifoManager: OptionalFifoManager
    package private(set) var commitTimingManager: OptionalCommitTimingManager
    package private(set) var contentTypeManager: OptionalContentTypeManager
    package private(set) var alphaModifierManager: OptionalAlphaModifierManager
    package private(set) var tearingControlManager: OptionalTearingControlManager
    package private(set) var colorRepresentationManager: OptionalColorRepresentationManager
    package private(set) var colorManager: OptionalColorManager
    package private(set) var xdgToplevelIconManager: OptionalXDGToplevelIconManager
    package private(set) var xdgActivation: OptionalXDGActivation
    package private(set) var compositorSessionManager: OptionalCompositorSessionManager
    package private(set) var pointerWarp: OptionalPointerWarp
    package private(set) var tabletManager: OptionalTabletManager
    package private(set) var relativePointerManager: OptionalRelativePointerManager
    package private(set) var pointerConstraints: OptionalPointerConstraints

    package init(
        xdgDecorationManager: OptionalXDGDecorationManager = .missing,
        xdgOutputManager: OptionalXDGOutputManager = .missing,
        viewporter: OptionalViewporter = .missing,
        presentation: OptionalPresentation = .missing,
        fractionalScaleManager: OptionalFractionalScaleManager = .missing,
        cursorShapeManager: OptionalCursorShapeManager = .missing,
        dataDeviceManager: OptionalDataDeviceManager = .missing,
        primarySelectionDeviceManager: OptionalPrimarySelectionDeviceManager = .missing,
        textInputManager: OptionalTextInputManager = .missing,
        linuxDmabuf: OptionalLinuxDmabuf = .missing,
        linuxDrmSyncobjManager: OptionalLinuxDrmSyncobjManager = .missing,
        fifoManager: OptionalFifoManager = .missing,
        commitTimingManager: OptionalCommitTimingManager = .missing,
        contentTypeManager: OptionalContentTypeManager = .missing,
        alphaModifierManager: OptionalAlphaModifierManager = .missing,
        tearingControlManager: OptionalTearingControlManager = .missing,
        colorRepresentationManager: OptionalColorRepresentationManager = .missing,
        colorManager: OptionalColorManager = .missing,
        xdgToplevelIconManager: OptionalXDGToplevelIconManager = .missing,
        xdgActivation: OptionalXDGActivation = .missing,
        compositorSessionManager: OptionalCompositorSessionManager = .missing,
        pointerWarp: OptionalPointerWarp = .missing,
        tabletManager: OptionalTabletManager = .missing,
        relativePointerManager: OptionalRelativePointerManager = .missing,
        pointerConstraints: OptionalPointerConstraints = .missing,
    ) {
        self.xdgDecorationManager = xdgDecorationManager
        self.xdgOutputManager = xdgOutputManager
        self.viewporter = viewporter
        self.presentation = presentation
        self.fractionalScaleManager = fractionalScaleManager
        self.cursorShapeManager = cursorShapeManager
        self.dataDeviceManager = dataDeviceManager
        self.primarySelectionDeviceManager = primarySelectionDeviceManager
        self.textInputManager = textInputManager
        self.linuxDmabuf = linuxDmabuf
        self.linuxDrmSyncobjManager = linuxDrmSyncobjManager
        self.fifoManager = fifoManager
        self.commitTimingManager = commitTimingManager
        self.contentTypeManager = contentTypeManager
        self.alphaModifierManager = alphaModifierManager
        self.tearingControlManager = tearingControlManager
        self.colorRepresentationManager = colorRepresentationManager
        self.colorManager = colorManager
        self.xdgToplevelIconManager = xdgToplevelIconManager
        self.xdgActivation = xdgActivation
        self.compositorSessionManager = compositorSessionManager
        self.pointerWarp = pointerWarp
        self.tabletManager = tabletManager
        self.relativePointerManager = relativePointerManager
        self.pointerConstraints = pointerConstraints
    }

    func destroy() {
        pointerConstraints.destroy()
        relativePointerManager.destroy()
        tabletManager.destroy()
        pointerWarp.destroy()
        compositorSessionManager.destroy()
        xdgActivation.destroy()
        xdgToplevelIconManager.destroy()
        colorManager.destroy()
        colorRepresentationManager.destroy()
        tearingControlManager.destroy()
        alphaModifierManager.destroy()
        contentTypeManager.destroy()
        commitTimingManager.destroy()
        fifoManager.destroy()
        linuxDrmSyncobjManager.destroy()
        linuxDmabuf.destroy()
        textInputManager.destroy()
        primarySelectionDeviceManager.destroy()
        dataDeviceManager.destroy()
        cursorShapeManager.destroy()
        fractionalScaleManager.destroy()
        presentation.destroy()
        viewporter.destroy()
        xdgOutputManager.destroy()
        xdgDecorationManager.destroy()
    }

    // swiftlint:disable:next cyclomatic_complexity
    package func invalidate(named interfaceName: String) {
        switch interfaceName {
        case "zxdg_decoration_manager_v1":
            retireOptionalGlobal(&xdgDecorationManager)
        case "zxdg_output_manager_v1":
            retireOptionalGlobal(&xdgOutputManager)
        case "wp_viewporter":
            retireOptionalGlobal(&viewporter)
        case "wp_presentation":
            retireOptionalGlobal(&presentation)
        case "wp_fractional_scale_manager_v1":
            retireOptionalGlobal(&fractionalScaleManager)
        case "wp_cursor_shape_manager_v1":
            retireOptionalGlobal(&cursorShapeManager)
        case "wl_data_device_manager":
            retireOptionalGlobal(&dataDeviceManager)
        case "zwp_primary_selection_device_manager_v1":
            retireOptionalGlobal(&primarySelectionDeviceManager)
        case "zwp_text_input_manager_v3":
            retireOptionalGlobal(&textInputManager)
        case "zwp_linux_dmabuf_v1":
            retireOptionalGlobal(&linuxDmabuf)
        case "wp_linux_drm_syncobj_manager_v1":
            retireOptionalGlobal(&linuxDrmSyncobjManager)
        case "wp_fifo_manager_v1":
            retireOptionalGlobal(&fifoManager)
        case "wp_commit_timing_manager_v1":
            retireOptionalGlobal(&commitTimingManager)
        case "wp_content_type_manager_v1":
            retireOptionalGlobal(&contentTypeManager)
        case "wp_alpha_modifier_v1":
            retireOptionalGlobal(&alphaModifierManager)
        case "wp_tearing_control_manager_v1":
            retireOptionalGlobal(&tearingControlManager)
        case "wp_color_representation_manager_v1":
            retireOptionalGlobal(&colorRepresentationManager)
        case "wp_color_manager_v1":
            retireOptionalGlobal(&colorManager)
        case "xdg_toplevel_icon_manager_v1":
            retireOptionalGlobal(&xdgToplevelIconManager)
        case "xdg_activation_v1":
            retireOptionalGlobal(&xdgActivation)
        case "xdg_session_manager_v1":
            retireOptionalGlobal(&compositorSessionManager)
        case "wp_pointer_warp_v1":
            retireOptionalGlobal(&pointerWarp)
        case "zwp_tablet_manager_v2":
            retireOptionalGlobal(&tabletManager)
        case "zwp_relative_pointer_manager_v1":
            retireOptionalGlobal(&relativePointerManager)
        case "zwp_pointer_constraints_v1":
            retireOptionalGlobal(&pointerConstraints)
        default:
            break
        }
    }
}

extension RawDisplayConnection {
    // swiftlint:disable function_body_length
    @safe
    package func bindOptionalGlobals(registry reg: OpaquePointer) throws -> OptionalGlobals {
        let rollback = OptionalGlobalRollback()

        let xdgDecorationManager = try bindXDGDecorationManagerIfPresent(registry: reg)
        rollback.append { xdgDecorationManager.destroy() }
        let xdgOutputManager = try bindXDGOutputManagerIfPresent(registry: reg)
        rollback.append { xdgOutputManager.destroy() }
        let viewporter = try bindViewporterIfPresent(registry: reg)
        rollback.append { viewporter.destroy() }
        let presentation = try bindPresentationIfPresent(registry: reg)
        rollback.append { presentation.destroy() }
        let fractionalScaleManager = try bindFractionalScaleManagerIfPresent(registry: reg)
        rollback.append { fractionalScaleManager.destroy() }
        let cursorShapeManager = try bindCursorShapeManagerIfPresent(registry: reg)
        rollback.append { cursorShapeManager.destroy() }
        let dataDeviceManager = try bindDataDeviceManagerIfPresent(registry: reg)
        rollback.append { dataDeviceManager.destroy() }
        let primarySelectionDeviceManager = try bindPrimarySelectionDeviceManagerIfPresent(
            registry: reg)
        rollback.append { primarySelectionDeviceManager.destroy() }
        let textInputManager = try bindTextInputManagerIfPresent(registry: reg)
        rollback.append { textInputManager.destroy() }
        let linuxDmabuf = try bindLinuxDmabufIfPresent(registry: reg)
        rollback.append { linuxDmabuf.destroy() }
        let linuxDrmSyncobjManager = try bindLinuxDrmSyncobjManagerIfPresent(registry: reg)
        rollback.append { linuxDrmSyncobjManager.destroy() }
        let fifoManager = try bindFifoManagerIfPresent(registry: reg)
        rollback.append { fifoManager.destroy() }
        let commitTimingManager = try bindCommitTimingManagerIfPresent(registry: reg)
        rollback.append { commitTimingManager.destroy() }
        let contentTypeManager = try bindContentTypeManagerIfPresent(registry: reg)
        rollback.append { contentTypeManager.destroy() }
        let alphaModifierManager = try bindAlphaModifierManagerIfPresent(registry: reg)
        rollback.append { alphaModifierManager.destroy() }
        let tearingControlManager = try bindTearingControlManagerIfPresent(registry: reg)
        rollback.append { tearingControlManager.destroy() }
        let colorRepresentationManager = try bindColorRepresentationManagerIfPresent(registry: reg)
        rollback.append { colorRepresentationManager.destroy() }
        let colorManager = try bindColorManagerIfPresent(registry: reg)
        rollback.append { colorManager.destroy() }
        let xdgToplevelIconManager = try bindXDGToplevelIconManagerIfPresent(registry: reg)
        rollback.append { xdgToplevelIconManager.destroy() }
        let xdgActivation = try bindXDGActivationIfPresent(registry: reg)
        rollback.append { xdgActivation.destroy() }
        let compositorSessionManager = try bindCompositorSessionManagerIfPresent(registry: reg)
        rollback.append { compositorSessionManager.destroy() }
        let pointerWarp = try bindPointerWarpIfPresent(registry: reg)
        rollback.append { pointerWarp.destroy() }
        let tabletManager = try bindTabletManagerIfPresent(registry: reg)
        rollback.append { tabletManager.destroy() }
        let relativePointerManager = try bindRelativePointerManagerIfPresent(registry: reg)
        rollback.append { relativePointerManager.destroy() }
        let pointerConstraints = try bindPointerConstraintsIfPresent(registry: reg)
        rollback.append { pointerConstraints.destroy() }

        rollback.disarm()
        return OptionalGlobals(
            xdgDecorationManager: xdgDecorationManager,
            xdgOutputManager: xdgOutputManager,
            viewporter: viewporter,
            presentation: presentation,
            fractionalScaleManager: fractionalScaleManager,
            cursorShapeManager: cursorShapeManager,
            dataDeviceManager: dataDeviceManager,
            primarySelectionDeviceManager: primarySelectionDeviceManager,
            textInputManager: textInputManager,
            linuxDmabuf: linuxDmabuf,
            linuxDrmSyncobjManager: linuxDrmSyncobjManager,
            fifoManager: fifoManager,
            commitTimingManager: commitTimingManager,
            contentTypeManager: contentTypeManager,
            alphaModifierManager: alphaModifierManager,
            tearingControlManager: tearingControlManager,
            colorRepresentationManager: colorRepresentationManager,
            colorManager: colorManager,
            xdgToplevelIconManager: xdgToplevelIconManager,
            xdgActivation: xdgActivation,
            compositorSessionManager: compositorSessionManager,
            pointerWarp: pointerWarp,
            tabletManager: tabletManager,
            relativePointerManager: relativePointerManager,
            pointerConstraints: pointerConstraints,
        )
    }
    // swiftlint:enable function_body_length
}
